# https://docs.docker.com/compose/gettingstarted/
# https://github.com/rajdeepd/docker-flask-mongo-todo
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3 python3-pip python-dev
ADD . /app
WORKDIR /app
COPY Pipfile.lock .
RUN pip3 install pipenv
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN pipenv install
